[package]
publish = false
name = "nsq-decode"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Derived artifact decode and report surface for NSQ."

[[bin]]
name = "nsq-decode"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
