#!/data/data/com.termux/files/usr/bin/bash
export TC="/data/data/com.termux/files/home/Braxon/state/full_android_language_toolchain"
export PYTHONHOME="/data/data/com.termux/files/home/Braxon/state/full_android_language_toolchain/install/python"
export LD_LIBRARY_PATH="/data/data/com.termux/files/home/Braxon/state/full_android_language_toolchain/install/braxon_android_overlay/lib:/data/data/com.termux/files/usr/lib:${LD_LIBRARY_PATH:-}"
unset PYTHONPATH
exec "/data/data/com.termux/files/home/Braxon/state/full_android_language_toolchain/install/python/bin/python3.16" "$@"
