[package]
publish = false
name = "nsq-universal-fetch"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
phf = { version = "0.11", optional = true }
ndarray = { version = "0.15", optional = true }
bitflags = "2"

[features]
brain-models = ["phf?/macros", "ndarray"]
default = ["brain-models"]
