use crate::{execute_language_operation, LanguageOperationReport};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

pub const COMPLETE_SEMANTIC_EXTRACTION_SCHEMA: &str =
    "braxon.nsq.complete_semantic_extraction_report.v1";
const CONTRACT_RELATIVE_PATH: &str = "config/nsq/complete_semantic_extraction_contract.json";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SemanticSurfaceProof {
    pub id: String,
    pub dialect: String,
    pub applicable: bool,
    pub operationally_proven: bool,
    pub proof_path: String,
    pub exact_requirement: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CompleteSemanticExtractionReport {
    pub schema: String,
    pub language_id: String,
    pub language_operation: LanguageOperationReport,
    pub surface_total: usize,
    pub proven_surface_total: usize,
    pub complete: bool,
    pub surfaces: Vec<SemanticSurfaceProof>,
    pub exact_completion_action: String,
}

#[derive(Debug, Deserialize)]
struct ExtractionContract {
    schema: String,
    #[serde(default)]
    required_semantic_surfaces: Vec<SurfaceDefinition>,
}

#[derive(Debug, Deserialize)]
struct SurfaceDefinition {
    id: String,
    dialect: String,
    meaning: String,
}

pub fn verify_complete_semantic_extraction(
    start: impl AsRef<Path>,
    language_id: &str,
    input: &str,
) -> Result<CompleteSemanticExtractionReport, String> {
    let root = resolve_root(start)?;
    let contract: ExtractionContract = read_json(&root.join(CONTRACT_RELATIVE_PATH))?;
    if contract.schema != "braxon.nsq.complete_semantic_extraction_contract.v1"
        || contract.required_semantic_surfaces.is_empty()
    {
        return Err("invalid complete semantic extraction contract".to_string());
    }
    let language_operation = execute_language_operation(&root, language_id, input)?;
    let proof_root = root.join("state/nsq/semantic_extraction").join(language_id);
    let surfaces = contract
        .required_semantic_surfaces
        .iter()
        .map(|surface| surface_proof(&proof_root, surface, &language_operation))
        .collect::<Vec<_>>();
    let proven_surface_total = surfaces
        .iter()
        .filter(|surface| surface.applicable && surface.operationally_proven)
        .count();
    let applicable_total = surfaces.iter().filter(|surface| surface.applicable).count();
    let complete = applicable_total > 0
        && applicable_total == proven_surface_total
        && language_operation.semantic_parse_ready
        && language_operation.native_materialization_ready;
    let missing = surfaces
        .iter()
        .filter(|surface| surface.applicable && !surface.operationally_proven)
        .map(|surface| surface.id.clone())
        .collect::<Vec<_>>();
    let exact_completion_action = if complete {
        format!(
            "All applicable NSQ semantic surfaces and the Android target materialization are proven for '{}'.",
            language_id
        )
    } else {
        format!(
            "Do not promote '{}'. Materialize content-addressed target proofs for [{}], then satisfy native materialization: {}",
            language_id,
            missing.join(", "),
            language_operation.exact_materialization_guidance
        )
    };
    Ok(CompleteSemanticExtractionReport {
        schema: COMPLETE_SEMANTIC_EXTRACTION_SCHEMA.to_string(),
        language_id: language_id.to_string(),
        language_operation,
        surface_total: applicable_total,
        proven_surface_total,
        complete,
        surfaces,
        exact_completion_action,
    })
}

fn surface_proof(
    proof_root: &Path,
    surface: &SurfaceDefinition,
    operation: &LanguageOperationReport,
) -> SemanticSurfaceProof {
    let proof_path = proof_root.join(format!("{}.json", surface.id));
    let operationally_proven = match surface.id.as_str() {
        "identity" => proof_path.is_file(),
        "lexical" => operation.semantic_parse_ready,
        "grammar" | "ast" | "types" | "control_flow" | "data_flow" | "ir" | "diagnostics"
        | "abi" | "assembly" | "object_format" | "debug" | "linking" | "target_constraints"
        | "materialization" | "recovery" => proof_path.is_file(),
        _ => false,
    };
    SemanticSurfaceProof {
        id: surface.id.clone(),
        dialect: surface.dialect.clone(),
        applicable: true,
        operationally_proven,
        proof_path: proof_path.display().to_string(),
        exact_requirement: if operationally_proven {
            format!("{} proof is present", surface.meaning)
        } else {
            format!(
                "{} requires a content-addressed proof at {} generated by the declared source-built extractor or Android target probe",
                surface.meaning,
                proof_path.display()
            )
        },
    }
}

fn resolve_root(start: impl AsRef<Path>) -> Result<PathBuf, String> {
    let canonical = start
        .as_ref()
        .canonicalize()
        .map_err(|error| format!("unable to resolve semantic extraction start: {error}"))?;
    canonical
        .ancestors()
        .find(|candidate| candidate.join(CONTRACT_RELATIVE_PATH).is_file())
        .map(Path::to_path_buf)
        .ok_or_else(|| "unable to locate complete semantic extraction contract".to_string())
}

fn read_json<T: for<'de> Deserialize<'de>>(path: &Path) -> Result<T, String> {
    let raw = fs::read_to_string(path)
        .map_err(|error| format!("failed to read '{}': {error}", path.display()))?;
    serde_json::from_str(&raw)
        .map_err(|error| format!("failed to parse '{}': {error}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repository_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("repository root")
    }

    #[test]
    fn lexical_parameter_parse_does_not_falsely_promote_unmaterialized_full_language_semantics() {
        let report = verify_complete_semantic_extraction(repository_root(), "rust", "fn main() {}")
            .expect("semantic extraction report");
        assert!(report.language_operation.semantic_parse_ready);
        assert!(!report.complete);
        assert!(report.proven_surface_total < report.surface_total);
        assert!(report.exact_completion_action.contains("Do not promote"));
    }
}
