#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
POLICY="$ROOT/config/toolchains/termux_nsq_intercept_policy.json"
STATE="$ROOT/state/termux_nsq_intercept"
BIN="$STATE/bin"
PROFILE="$STATE/profile.d/braxon-nsq-intercept.sh"
MANIFEST="$STATE/calibration_manifest.json"
HASHES="$STATE/SHA256SUMS"
RESOLVER="$ROOT/scripts/toolchains/resolve_braxon_repository_tool.sh"
MODE="${1:-status}"

fail() { printf '%s\n' "braxon-termux-calibrate: $*" >&2; exit 1; }
[ -f "$POLICY" ] || fail "intercept policy is missing: $POLICY"
[ -x "$RESOLVER" ] || fail "repository-tool resolver is missing or not executable: $RESOLVER"

require_target_or_override() {
  machine="$(uname -m 2>/dev/null || printf unknown)"
  system="$(uname -s 2>/dev/null || printf unknown)"
  if [ "$machine" != "aarch64" ] || [ "$system" != "Linux" ]; then
    [ "${BRAXON_ALLOW_NON_TARGET_CALIBRATION:-0}" = "1" ] || fail "requires Android/AArch64; use BRAXON_ALLOW_NON_TARGET_CALIBRATION=1 only for wrapper-generation tests"
  fi
}

intercept_binary() {
  if [ -n "${BRAXON_INTERCEPT_EXECUTABLE:-}" ] && [ -x "$BRAXON_INTERCEPT_EXECUTABLE" ]; then
    printf '%s\n' "$BRAXON_INTERCEPT_EXECUTABLE"
    return 0
  fi
  if [ -x "$ROOT/target/release/Braxon" ]; then
    printf '%s\n' "$ROOT/target/release/Braxon"
    return 0
  fi
  fail "no release Braxon interceptor exists; build it from this repository with cargo build --release --locked --offline or set BRAXON_INTERCEPT_EXECUTABLE"
}

tool_language() {
  case "$1" in
    rustc|cargo|rustdoc|rustfmt|clippy-driver) printf '%s\n' rust ;;
    clang|clang++) printf '%s\n' c ;;
    ld.lld|llvm-ar|llvm-ranlib|llvm-nm|llvm-objdump|llvm-readelf|llvm-strip) printf '%s\n' elf ;;
    python3) printf '%s\n' python ;;
    guile) printf '%s\n' guile ;;
    zig) printf '%s\n' zig ;;
    *) fail "no declared NSQ language binding for tool '$1'" ;;
  esac
}

write_wrapper() {
  tool="$1"
  language="$(tool_language "$tool")"
  cat > "$BIN/$tool" <<EOF
#!/usr/bin/env sh
set -eu
ROOT='$ROOT'
INTERCEPT="\${BRAXON_INTERCEPT_EXECUTABLE:-\$ROOT/target/release/Braxon}"
RESOLVER="\$ROOT/scripts/toolchains/resolve_braxon_repository_tool.sh"
[ -x "\$INTERCEPT" ] || { printf '%s\\n' 'NSQ intercept binary is unavailable; refusing direct tool fallback' >&2; exit 126; }
[ -x "\$RESOLVER" ] || { printf '%s\\n' 'Braxon repository-tool resolver is unavailable; refusing direct tool fallback' >&2; exit 126; }
"\$INTERCEPT" language '$language' '$(printf '%s' "$tool")' "\$*" >/dev/null
exec "\$RESOLVER" exec '$(printf '%s' "$tool")' "\$@"
EOF
  chmod 0755 "$BIN/$tool"
}

write_pkg_guard() {
  real="$1"
  cat > "$BIN/pkg" <<EOF
#!/usr/bin/env sh
set -eu
case "\${1:-}" in
  install|reinstall|upgrade|uninstall|remove|autoremove)
    [ "\${BRAXON_ALLOW_CALIBRATED_PKG_MUTATION:-0}" = "1" ] || { printf '%s\\n' 'Blocked package mutation: verify calibration, set BRAXON_ALLOW_CALIBRATED_PKG_MUTATION=1 for an explicit action, then rerun braxon_termux_calibrate.sh calibrate.' >&2; exit 126; }
    ;;
esac
exec '$real' "\$@"
EOF
  chmod 0755 "$BIN/pkg"
}

calibrate() {
  require_target_or_override
  mkdir -p "$BIN" "$(dirname "$PROFILE")"
  manifest_tmp="$MANIFEST.tmp.$$"
  : > "$manifest_tmp"
  {
    printf '{\n'
    printf '  "schema":"braxon.termux.nsq_calibration_manifest.v2",\n'
    printf '  "target_machine":"%s",\n' "$(uname -m 2>/dev/null || printf unknown)"
    printf '  "page_size":"%s",\n' "$(getconf PAGESIZE 2>/dev/null || printf unknown)"
    printf '  "ambient_termux_tool_fallback":false,\n'
    printf '  "tools":[\n'
  } >> "$manifest_tmp"
  first=1
  for tool in rustc cargo rustdoc rustfmt clippy-driver clang clang++ ld.lld llvm-ar llvm-ranlib llvm-nm llvm-objdump llvm-readelf llvm-strip python3 guile zig; do
    resolution="$("$RESOLVER" status "$tool")" || {
      rm -f "$manifest_tmp"
      fail "repository-built '$tool' is not ready; complete its declared source-build and verification route before calibration. Ambient Termux fallback is prohibited"
    }
    write_wrapper "$tool"
    [ "$first" = 1 ] || printf ',\n' >> "$manifest_tmp"
    first=0
    printf '    %s' "$resolution" >> "$manifest_tmp"
  done
  printf '\n  ]\n}\n' >> "$manifest_tmp"
  mv "$manifest_tmp" "$MANIFEST"
  pkg_real="$(command -v pkg 2>/dev/null || true)"
  [ -z "$pkg_real" ] || write_pkg_guard "$pkg_real"
  cat > "$PROFILE" <<EOF
# Generated by scripts/braxon_termux_calibrate.sh.
# Every declared language/tool route resolves only to a verified repository-built artifact.
export PATH='$BIN':"\$PATH"
EOF
  (cd "$STATE" && find bin profile.d -type f -print0 | sort -z | xargs -0 sha256sum; sha256sum calibration_manifest.json) > "$HASHES"
  printf '%s\n' "CALIBRATED_OVERLAY=$BIN"
  printf '%s\n' "SOURCE_THIS_PROFILE=$PROFILE"
}

verify() {
  [ -f "$HASHES" ] || fail "no calibration hash manifest; run calibrate after all repository-built tool routes are verified"
  (cd "$STATE" && sha256sum -c SHA256SUMS)
}

heal() {
  [ "${BRAXON_ALLOW_NSQ_SELF_HEAL:-0}" = "1" ] || fail "set BRAXON_ALLOW_NSQ_SELF_HEAL=1 after reviewing the current calibration state"
  calibrate
  verify
}

case "$MODE" in
  calibrate) calibrate ;;
  verify) verify ;;
  heal) heal ;;
  status) printf 'policy=%s\nstate=%s\nresolver=%s\nintercept=%s\n' "$POLICY" "$STATE" "$RESOLVER" "$(intercept_binary)" ;;
  *) fail "usage: $0 [status|calibrate|verify|heal]" ;;
esac
