[package]
publish = false
name = "nsq-optimize"
version = "0.2.0"
edition = "2021"
license.workspace = true
authors.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Optimizer report generator for canonical NSQ corpora."

[dependencies]
serde.workspace = true
serde_json.workspace = true
