[package]
publish = false
name = "nsq-calibrate"
version = "0.2.0"
edition = "2021"
license.workspace = true
authors.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Calibration lock generator for optimized NSQ corpora."

[dependencies]
serde.workspace = true
serde_json.workspace = true
