[package]
publish = false
name = "nsq-ir"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true
rust-version.workspace = true
readme = "README.md"
description = "Registry-path definitions for the NSQ intermediate representation."

[lib]
path = "src/lib.rs"

[[bin]]
name = "nsq-ir"
path = "src/main.rs"
